name: JoinLeaveMessages
version: '${project.version}'
main: fun.northy.joinleavemessages.general.JoinLeaveMessages
softdepend: [ PlaceholderAPI ]
authors: [ northy ]
description: Plugin na customowe wiadomości przy wchodzeniu i wychodzeniu na serwer
website: northy.fun
commands:
  jlm:
    aliases: ['joinleavemessages', 'jlmessages']
