name: JoinLeaveMessages
version: '${project.version}'
main: fun.northy.joinleavemessages.general.JoinLeaveMessages
softdepend: [ PlaceholderAPI ]
authors: [ northy ]
description: Prosty plugin do zarzadzania wiadomosciami o wejsciu i wyjsciu
website: northy.fun
commands:
  jlm:
    aliases: ['joinleavemessages', 'jlmessages']
